all: tp2
	
tp2:
	javac src/lexer/*.java
	javac src/symbols/*.java
	javac src/inter/*.java
	javac src/parser/*.java
	javac src/main/*.java

.PHONY: clean
clean:
	rm -rf src/lexer/*.class
	rm -rf src/symbols/*.class
	rm -rf src/inter/*.class
	rm -rf src/parser/*.class
	rm -rf src/main/*.class
